Repository hmcts/darts-shared-infrastructure, pull requests merged in 2023-12, with the labels that each got.

#117 DMP-1590-Demo/ITHC/Test-Admin-Group
  locals.tf
Labels: destroy

#118 Darts-Mig-Resources-On-STG-Prod
  database.tf
  demo.tfvars
  firewall.tf
  ithc.tfvars
  key-vaults.tf
  locals.tf
  migration-blob-storage.tf
  migration-vms.tf
  networking.tf
  prod.tfvars
  redis.tf
  resource-groups.tf
  role-assignment.tf
  stg.tfvars
  test.tfvars
  variables.tf
  virtual-machine.tf
Labels: destroy

#119 fix: issues with prod plan
  migration-vms.tf
  prod.tfvars
Labels: destroy

#120 Removing-Mig-Resource-Group
  migration-blob-storage.tf
Labels: destroy

#123 fix: update redis config & move to existing rg
  redis.tf
Labels: destroy

#124 update sku and size
  demo.tfvars
Labels: destroy

#127 fix: update redis module ref
  key-vaults.tf
  redis.tf
Labels: destroy

#126 DMP-1762-Ubuntu-Server-Mongo-DB
  prod.tfvars
Labels: add-or-update

#125 DMP-1689: Make provision for a new secret
  .gitignore
  key-vaults.tf
  locals.tf
  variables.tf
Labels: add-or-update

#128 DMP-1762-Ubuntu-Machine
  prod.tfvars
Labels: add-or-update

#129 DMP-1689 - Add a README for the file upload
  README.md
Labels: no-changes
