Repository hmcts/darts-shared-infrastructure, pull requests merged in 2024-06, with the labels that each got.

#248 feat-provider-update
  state.tf
Labels: stg/add-or-update, prod/add-or-update

#247 feat-ora-vm-traffic
  alerts.tf
  networking.tf
Labels: stg/destroy, prod/destroy

#251 feat-removing-test-vms
  modernisation-network.tf
  modernisation-vms.tf
Labels: stg/add-or-update, prod/add-or-update

#252 Feat-test-vm-fix
  modernisation-vms.tf
Labels: stg/add-or-update, prod/add-or-update

#253 feat-network-security-rules
  networking.tf
Labels: stg/add-or-update, prod/add-or-update

#254 feat-storage-acc-private-endpoints
  blob-storage.tf
  locals.tf
  variables.tf
Labels: stg/add-or-update, prod/add-or-update

#213 feat-logic-app
  event-grid.tf
  logic-app.tf
Labels: stg/destroy, plan-on-prod, prod/destroy

#255 feat: added bare logic app standard
  blob-storage.tf
  locals.tf
  logic-app.tf
  networking.tf
  prod.tfvars
  test.tfvars
Labels: stg/destroy, prod/destroy

#256 feat-removing-network-rules
  networking.tf
Labels: stg/destroy, prod/destroy

#257 feat-malware-scanning-cap
  migration-blob-storage.tf
Labels: stg/add-or-update, prod/add-or-update
