Repository hmcts/darts-shared-infrastructure, pull requests merged in 2024-01, with the labels that each got.

#130 DTSPO-15909 - migrated Application Insights
  app-insights.tf
Labels: add-or-update

#133 DMP-1875-Darts-ITHC-Test
  Jenkinsfile_CNP
Labels: no-changes

#134 feat: added test storage account
  key-vaults.tf
  migration-blob-storage.tf
  prod.tfvars
Labels: add-or-update

#135 DDM-88-Linux-Machine-For-Oracle
  migration-vms.tf
  prod.tfvars
  variables.tf
Labels: no-changes

#136 Ddm-88-oracle-vm
  migration-vms.tf
Labels: no-changes

#139 Ddm 88 oracle vm
  migration-blob-storage.tf
Labels: destroy

#141 Ddm 88 oracle vm
  migration-vms.tf
Labels: no-changes

#142 Ddm 88 oracle vm
  migration-vms.tf
Labels: no-changes

#132 DDM-56-Linux-Availability-Zones
  migration-vms.tf
  prod.tfvars
  variables.tf
Labels: no-changes

#148 feat: domain join windows hosts
  locals.tf
  migration-vms.tf
  virtual-machine.tf
Labels: add-or-update

#149 fix: specify Entra ID Domain Services as the DNS Servers for the migration vnet
  networking.tf
Labels: add-or-update
