Repository hmcts/darts-shared-infrastructure, pull requests merged in 2024-02, with the labels that each got.

#150 DMP-1876-Test-Env
  Jenkinsfile_CNP
Labels: no-changes

#151 DDM-318-Oracle-server-downgrade
  migration-vms.tf
Labels: no-changes

#154 feat: add external services subnet
  locals.tf
  networking.tf
  prod.tfvars
  variables.tf
Labels: no-changes

#155 feat: expand migration_vms variable to specify data disk size
  migration-vms.tf
  prod.tfvars
  variables.tf
Labels: destroy

#152 feat-remove-windows-11
  virtual-machine.tf
Labels: destroy

#153 feat-windows-assesment
  migration-vms.tf
  prod.tfvars
  test.tfvars
  variables.tf
  virtual-machine.tf
Labels: destroy

#156 feat-update-windows-assessment-vm-name
  prod.tfvars
Labels: no-changes

#159 Remove-dartsmig05
  prod.tfvars
Labels: no-changes

#160 recreate-dartsmig05
  prod.tfvars
Labels: no-changes

#161 Setting advanced Redis settings for demo
  demo.tfvars
  redis.tf
  variables.tf
Labels: no-changes

#163 ddm-365 add dets db to felible server
  database.tf
  locals.tf
Labels: add-or-update

#164 fix: rework migration vms to use extended subnet
  locals.tf
  migration-vms.tf
  networking.tf
  prod.tfvars
  variables.tf
Labels: no-changes

#166 DMP-2426-Modernisation-VM
  modernisation-vms.tf
  stg.tfvars
Labels: add-or-update

#167 Dmp-2426-modernisation-vm
  stg.tfvars
Labels: add-or-update

#168 Dmp-2426-reduce-midmock-cpus
  stg.tfvars
Labels: add-or-update

#169 fix: missing AAD SSH extensions
  migration-vms.tf
  prod.tfvars
  stg.tfvars
Labels: add-or-update
