Repository hmcts/darts-shared-infrastructure, pull requests merged in 2024-03, with the labels that each got.

#171 feat-assurance-vm-tooling
  networking.tf
Labels: destroy

#172 Feat-vm-tooling-installs
  networking.tf
Labels: add-or-update

#170 feat-defender-scanning-cap
  migration-blob-storage.tf
Labels: no-changes

#173 add darts migration backup policy
  migration-backup-policy.tf
Labels: add-or-update

#175 increase retention to 7 days
  migration-backup-policy.tf
Labels: add-or-update

#176 add oracle vms
  migration-backup-policy.tf
Labels: add-or-update

#177 fix: backup & fmt
  migration-backup-policy.tf
  migration-blob-storage.tf
  modernisation-vms.tf
Labels: add-or-update

#179 add all mig vms to backup policy
  migration-backup-policy.tf
Labels: add-or-update

#182 allow outbound internet
  networking.tf
Labels: add-or-update

#183 fix error
  migration-backup-policy.tf
Labels: add-or-update

#181 DMP-1904-Perf-Test-VM
  migration-backup-policy.tf
  modernisation-vms.tf
  test.tfvars
  variables.tf
Labels: add-or-update

#185 Dmp-1904-Remove-Backup-Policy
  migration-backup-policy.tf
Labels: add-or-update

#184 remove outbound
  networking.tf
Labels: add-or-update

#186 Feat-migration-backup-policy
  migration-backup-policy.tf
  modernisation-vms.tf
  test.tfvars
Labels: add-or-update

#187 DDM-431-Oracle-vm-ram
  migration-vms.tf
Labels: add-or-update

#189 feat-perftest-vms
  locals.tf
  modernisation-vms.tf
Labels: add-or-update

#191 add replica db
  database.tf
  locals.tf
Labels: add-or-update

#192 Feat pertest vms
  locals.tf
  modernisation-network.tf
  modernisation-vms.tf
  test.tfvars
  variables.tf
Labels: add-or-update

#194 Feat-pertest-vms
  modernisation-network.tf
Labels: add-or-update

#195 Feat-pertest-vms
  modernisation-network.tf
Labels: add-or-update

#198 Feat-perftest-network
  modernisation-network.tf
Labels: add-or-update

#201 Reverting demo Redis back to Standard
  demo.tfvars
Labels: add-or-update

#200 Feat-perftest-aad
  modernisation-vms.tf
Labels: add-or-update

#203 feat-event-grid
  event-grid.tf
  logic-app.tf
Labels: add-or-update

#193 DDM-443-Postgres-Storage
  database.tf
Labels: add-or-update

#204 Feat-event-grid
  event-grid.tf
Labels: destroy
