Repository hmcts/darts-shared-infrastructure, pull requests merged in 2024-09, with the labels that each got.

#277 Try to reconcile db extensions
  database.tf
Labels: stg/add-or-update, prod/add-or-update

#278 Update demo.tfvars
  demo.tfvars
Labels: stg/add-or-update, prod/add-or-update

#280 Update demo.tfvars
  demo.tfvars
Labels: stg/add-or-update, prod/add-or-update

#283 Feat-azure-diagnostic
  database.tf
  demo.tfvars
  ithc.tfvars
  log-analytics.tf
  prod.tfvars
  stg.tfvars
  test.tfvars
  variables.tf
Labels: stg/add-or-update, prod/add-or-update

#284 feat-audit-log
  database.tf
Labels: stg/add-or-update, prod/add-or-update

#287 feat-demo-law-fix
  demo.tfvars
Labels: stg/add-or-update

#288 DTSPO-18893 - deploying AMA to the nonprod Darts VMs
  migration-blob-storage.tf
  state.tf
  stg.tfvars
  variables.tf
  virtual-machine.tf
Labels: stg/add-or-update, prod/add-or-update

#289 DTSPO-18893 - updated config to deploy AMA for all stg VMs
  modernisation-vms.tf
  test.tfvars
Labels: stg/add-or-update, prod/add-or-update

#290 DTSPO-18894 - added bootsrap module to install Azure monitor Agent
  migration-vms.tf
  prod.tfvars
  variables.tf
Labels: stg/add-or-update, prod/add-or-update

#291 DTSPO-18894 - removing AMA from prddartsmigora01
  migration-vms.tf
Labels: stg/add-or-update, prod/destroy

#292 DTSPO-18894 - allowing outbound traffic for Azure Monitor Logs
  networking.tf
Labels: stg/add-or-update, prod/add-or-update
